PODS-8821 - Add Event 25/24
hmrc/pension-scheme-event-reporting pull request #188
Opened 2023-11-07 15:43 UTC by LauraToddCodes

2023-11-07 16:06 UTC, PavelVjalicin requested changes
Does this code change required for this ticket? What impact does it have on frontend?

2023-11-07 16:06 UTC, PavelVjalicin commented on app/models/enumeration/EventType.scala
> +    override val order = 19
Order should be 20 here.

2023-11-07 16:16 UTC, LauraToddCodes commented
> Is this code change required for the ticket? What impact does it have on frontend?

It does seem to be needed, if you run the FE locally without this change then you'll get a 500 error after the Member's details page where it cannot find Event 24

2023-11-07 16:32 UTC, PavelVjalicin commented
> > Is this code change required for the ticket? What impact does it have on frontend?
> 
> It does seem to be needed, if you run the FE locally without this change then you'll get a 500 error after the Member's details page where it cannot find Event 24

Sounds good.

2023-11-13 14:00 UTC, PavelVjalicin approved these changes
LGTM

2023-11-13 14:18 UTC, merged